### ISSUE TITLE
Tmux title wrong when folder has "." in it

### ISSUE THREAD

**Issue by TSFoster** [dhruvasagar/vim-prosession#28]
My tmux window name drops everything after the ".". I come across then when working in "~/.dotfiles" or ~/example.directory.name".

I think you have tried to fix it before with a146ea2, but it's not working for me. I tried fixing it myself but am not very used to VimL, so I wasn't able to do it without introducing a weird bug.

**Comment by dhruvasagar** [comment]
Interesting I don't think I have noticed / experienced this myself or I may have overlooked it. I believe your PR fixes this ? Kindly close this if it does, I merged your PR.

Thanks for your contribution!

**Comment by TSFoster** [comment]
No, my PR didn't fix it, it was just to customise the title. I'll have a look at this again.
